import{S as c,i as h,a as m}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(s){if(s.ep)return;s.ep=!0;const a=r(s);fetch(s.href,a)}})();const p="/goit-js-hw-12/assets/alert-6c35a70b.svg",d=document.querySelector(".form"),o=document.querySelector(".get-more-btn"),n={url:"https://pixabay.com/api/",searchParams:{key:"42136194-d83aa60221700b9cbb1b7b2b9",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:1},prevSearchTerm:"",searchPhotosBtn:document.querySelector(".search-btn"),searchTerm:document.querySelector(".searchTerm"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),totalHits:0,simpleGallery:new c(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250}),startSearch(e){e.preventDefault();const t=this.searchTerm.value.trim();if(t.length<3){this.showAlert("Please, enter search term!");return}if(t===this.prevSearchTerm){this.showAlert("You have already searched for this term.");return}this.prevSearchTerm=t,this.gallery.innerHTML="",this.searchParams.q=t,this.searchParams.page=1,this.fetchPhotos()},loadMorePhotos(){this.searchParams.page+=1,this.fetchPhotos()},renderPhotos(e){if(e.total===0){this.showAlert("Sorry, there are no images matching your search query. Please try again!"),this.showLoaderAndButtons(!1),o.style.display="none";return}this.totalHits=e.totalHits;const t=e.hits.map(r=>`<a class="gallery-link" href="${r.largeImageURL}">
                <span class="gallery-item"><img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}" /></span>
                <span class="img-stat">
                <span class="img-stat-item"><span class="img-stat-title">Likes</span><span class="img-stat-val">${r.likes}</span></span>
                <span class="img-stat-item"><span class="img-stat-title">Views</span><span class="img-stat-val">${r.views}</span></span>
                <span class="img-stat-item"><span class="img-stat-title">Comments</span><span class="img-stat-val">${r.comments}</span></span>
                <span class="img-stat-item"><span class="img-stat-title">Downloads</span><span class="img-stat-val">${r.downloads}</span></span>
                </span>
                </a>`).join("");this.gallery.insertAdjacentHTML("beforeend",t),this.simpleGallery.refresh(),this.scrollTop()},scrollTop(){if(this.searchParams.page>1){const e=document.querySelector(".gallery-link");if(e){const t=e.getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}}},showLoaderAndButtons(e=!0){this.loader.style.display=e?"inline-block":"none",o.style.display=e?"none":"block",this.searchPhotosBtn.disabled=e,e===!1&&(this.searchParams.page===1&&this.totalHits>1&&(o.style.display="block"),Math.ceil(this.totalHits/this.searchParams.per_page)===this.searchParams.page&&(o.style.display="none",this.showAlert("We're sorry, but you've reached the end of search results.")))},showAlert(e){h.show({position:"center",iconUrl:p,messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,message:e})},async fetchPhotos(){this.showLoaderAndButtons();try{const e=await m.get(this.url,{params:this.searchParams});this.renderPhotos(e.data)}catch(e){this.showAlert(e.message)}this.showLoaderAndButtons(!1)}};d.addEventListener("submit",e=>n.startSearch(e));o.addEventListener("click",()=>n.loadMorePhotos());
//# sourceMappingURL=commonHelpers.js.map
